### ISSUE TITLE
character block parsing

### ISSUE THREAD

**Issue by caisilus** [mmcs-ruby/ruber_dialog#11]
# Character block looks like:
    Characters:
    Gandalf
    Frodo
    Bilbo
# Tasks
- [ ] error validation(forbidden expressions, reserved words)
- [ ] parser configuration
- [ ] create models to contain information about characters(Character model)
- [ ] character block parsing to array of Characters
