### ISSUE TITLE
description block parsing

### ISSUE THREAD

**Issue by caisilus** [mmcs-ruby/ruber_dialog#12]
# Description block looks like:
    {Приветствие}
    Описание: В комнате на столе есть: эль и пиво, двоеточия 
    и переносы строк.
    Гендальф: Возьми кольцо, Фродо.
# Tasks
- [ ] error validation(forbidden expressions, reserved words)
- [ ] parser configuration
- [ ] create models to contain information about lines
- [ ] description block parsing
