### ISSUE TITLE
responses block parsing

### ISSUE THREAD

**Issue by caisilus** [mmcs-ruby/ruber_dialog#13]
# Responses block looks like:
    [Да->{Поход в Мордор} 
    | Нет, я не хочу носить кольцо -> {Конец игры}]
# Tasks
- [ ] error validation(forbidden expressions, reserved words)
- [ ] parser configuration
- [ ] create models to contain information about responses
- [ ] responses block parsing
